/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractOptions, Options } from "web3-eth-contract";
import { Block } from "web3-eth";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { Callback, TransactionObject } from "./types";

export class TollToken extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    balanceOf(owner: string): TransactionObject<string>;

    isMinter(account: string): TransactionObject<boolean>;

    allowance(owner: string, spender: string): TransactionObject<string>;

    isTollingBooth(tollingBooth: string): TransactionObject<boolean>;

    approve(
      spender: string,
      value: number | string
    ): TransactionObject<boolean>;

    transferFrom(
      from: string,
      to: string,
      value: number | string
    ): TransactionObject<boolean>;

    increaseAllowance(
      spender: string,
      addedValue: number | string
    ): TransactionObject<boolean>;

    mint(to: string, value: number | string): TransactionObject<boolean>;

    addMinter(account: string): TransactionObject<void>;

    renounceMinter(): TransactionObject<void>;

    decreaseAllowance(
      spender: string,
      subtractedValue: number | string
    ): TransactionObject<boolean>;

    transfer(to: string, value: number | string): TransactionObject<boolean>;

    withdrawFromBooth(
      tollingBooth: string,
      amount: number | string
    ): TransactionObject<void>;

    registerTollingBooth(tollingBooth: string): TransactionObject<void>;

    setTollAmount(amount: number | string): TransactionObject<void>;

    paytoll(
      amount: number | string,
      vehicleId: number | string,
      vehicleOwner: string,
      tollBooth: string
    ): TransactionObject<boolean>;

    name(): TransactionObject<string>;
    totalSupply(): TransactionObject<string>;
    decimals(): TransactionObject<string>;
    symbol(): TransactionObject<string>;
    tollAmount(): TransactionObject<string>;
  };
  events: {
    MinterAdded(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    MinterRemoved(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    Transfer(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    Approval(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
